### ISSUE TITLE
Build problem on Alpine linux 3.21

### ISSUE THREAD

**Issue by RomanenkoDenys** [falcosecurity/falco#3594]
**Describe the bug**

Falco binary cannot build on Alpine linux 3.21/3.22
**How to reproduce it**

```
docker run -it alpine:3.22
apk add g++ gcc cmake make git bash perl linux-headers autoconf automake m4 libtool elfutils-dev libelf-static binutils bpftool clang
git clone https://github.com/falcosecurity/falco.git -b 0.41.0
cd falco
mkdir -p build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DRIVER=OFF -DCPACK_GENERATOR=TGZ -DBUILD_BPF=OFF -DBUILD_FALCO_MODERN_BPF=ON -DBUILD_WARNINGS_AS_ERRORS=OFF -DFALCO_VERSION=0.41.0 -DUSE_BUNDLED_DEPS=ON /src/falco
make package
```

Error:
```
[  1%] Building CXX object third_party/abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/internal/low_level_alloc.cc.o
In file included from /src/falco/build/grpc-prefix/src/grpc/third_party/abseil-cpp/absl/base/internal/low_level_alloc.cc:26:
/src/falco/build/grpc-prefix/src/grpc/third_party/abseil-cpp/absl/base/internal/direct_mmap.h:75:25: error: 'off64_t' has not been declared
   75 |                         off64_t offset) noexcept {
      |                         ^~~~~~~
make[5]: *** [third_party/abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/build.make:79: third_party/abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/internal/low_level_alloc.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:1986: third_party/abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/grpc.dir/build.make:86: grpc-prefix/src/grpc-stamp/grpc-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1054: CMakeFiles/grpc.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
**Expected behaviour**

Succesful build.

**Screenshots**

**Environment**

- Falco version: 0.41.0

- System info:

- Cloud provider or hardware configuration:
- OS: Alpine linux 3.22

- Kernel:

- Installation method:

**Additional context**

**Comment by RomanenkoDenys** [comment]
To fix that error i change `off64_t offset) noexcept {` to `off_t offset) noexcept {`

**Comment by FedeDP** [comment]
Hi! We have a very similar patch for abseil-cpp: https://github.com/falcosecurity/falco/blob/master/cmake/modules/grpc.cmake#L180

But, since you are using the bundled grpc version, i think this is most probably a compiler issue (you'll probably have a very recent compiler that perhaps needs more adaption).
I think that appending a new patch won't have any side effect; are you willing to open a PR with the fix?

**Comment by RomanenkoDenys** [comment]
I'll try to build on several computers with the same effect. I'll open PR, thanks.

**Comment by derekhjray** [comment]
I have add a patch to grpc.cmake file, looks fine for me
```
		if(MUSL_OPTIMIZED_BUILD)
			execute_process(
				COMMAND grep -q "set(CMAKE_REQUIRED_DEFINITIONS -D_LARGEFILE64_SOURCE=1)" "${GRPC_SRC}/CMakeLists.txt"
				RESULT_VARIABLE GREP_RESULT
				OUTPUT_QUIET
				ERROR_QUIET
			)

			if(NOT GREP_RESULT EQUAL 0)
				file(WRITE ${CMAKE_CURRENT_BINARY_DIR}/grpc_patch.sh "#!/bin/bash
sed -i '/if(gRPC_BACKWARDS_COMPATIBILITY_MODE)/i \\
#\\
# Check to see if we have large file support\\
#\\
include(CheckTypeSize)\\
set(CMAKE_REQUIRED_DEFINITIONS -D_LARGEFILE64_SOURCE=1)\\
# We add these other definitions here because alpine musl-libc does not support off64_t by default\\
check_type_size(off64_t OFF64_T)\\
if(HAVE_OFF64_T)\\
	add_definitions(-D_LARGEFILE64_SOURCE=1)\\
endif()\\
set(CMAKE_REQUIRED_DEFINITIONS) # clear variable\\
' ${GRPC_SRC}/CMakeLists.txt
")
				set(GRPC_PATCH_CMD
					${GRPC_PATCH_CMD}
					&&
					chmod +x ${CMAKE_CURRENT_BINARY_DIR}/grpc_patch.sh
					&&
					${CMAKE_CURRENT_BINARY_DIR}/grpc_patch.sh
				)
			endif()
		endif()
```

**Comment by RomanenkoDenys** [comment]
Looks good for me
