### PR TITLE
fix(cmake): fix abseil-cpp under alpine build

### LINKED ISSUE #3594: Build problem on Alpine linux 3.21
**Describe the bug**

Falco binary cannot build on Alpine linux 3.21/3.22
**How to reproduce it**

```
docker run -it alpine:3.22
apk add g++ gcc cmake make git bash perl linux-headers autoconf automake m4 libtool elfutils-dev libelf-static binutils bpftool clang
git clone https://github.com/falcosecurity/falco.git -b 0.41.0
cd falco
mkdir -p build
cd build
cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_DRIVER=OFF -DCPACK_GENERATOR=TGZ -DBUILD_BPF=OFF -DBUILD_FALCO_MODERN_BPF=ON -DBUILD_WARNINGS_AS_ERRORS=OFF -DFALCO_VERSION=0.41.0 -DUSE_BUNDLED_DEPS=ON /src/falco
make package
```

Error:
```
[  1%] Building CXX object third_party/abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/internal/low_level_alloc.cc.o
In file included from /src/falco/build/grpc-prefix/src/grpc/third_party/abseil-cpp/absl/base/internal/low_level_alloc.cc:26:
/src/falco/build/grpc-prefix/src/grpc/third_party/abseil-cpp/absl/base/internal/direct_mmap.h:75:25: error: 'off64_t' has not been declared
   75 |                         off64_t offset) noexcept {
      |                         ^~~~~~~
make[5]: *** [third_party/abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/build.make:79: third_party/abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/internal/low_level_alloc.cc.o] Error 1
make[4]: *** [CMakeFiles/Makefile2:1986: third_party/abseil-cpp/absl/base/CMakeFiles/absl_malloc_internal.dir/all] Error 2
make[3]: *** [Makefile:136: all] Error 2
make[2]: *** [CMakeFiles/grpc.dir/build.make:86: grpc-prefix/src/grpc-stamp/grpc-build] Error 2
make[1]: *** [CMakeFiles/Makefile2:1054: CMakeFiles/grpc.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
```
**Expected behaviour**

Succesful build.

**Screenshots**

**Environment**

- Falco version: 0.41.0

- System info:

- Cloud provider or hardware configuration:
- OS: Alpine linux 3.22

- Kernel:

- Installation method:

**Additional context**

### PR DESCRIPTION
**Pull request by RomanenkoDenys**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

> /kind cleanup

> /kind design

> /kind documentation

> /kind failing-test

> /kind feature

> /kind release

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area build

> /area engine

> /area tests

> /area proposals

> /area CI

**What this PR does / why we need it**:

This PR fixes build on Alpine Linux.

**Which issue(s) this PR fixes**:

Fixes #3594

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note
NONE
```

### CODE REVIEW

**Comment by FedeDP** [comment]
Hi! Thanks, great fix!
Can you fix code format? See https://github.com/falcosecurity/falco/blob/master/Contributing.md#enforce-coding-style- :) 
Thanks!
/milestone 0.42.0

**Comment by RomanenkoDenys** [comment]
@FedeDP thanks, i'll fix formatting tomorrow.

**Comment by RomanenkoDenys** [comment]
fixed

**Review by FedeDP — APPROVED** [review]
/approve

**Comment by RomanenkoDenys** [comment]
I have one more general question. As i see, falco has ability to build with musl, mostly static. How falco interoperate with plugins, which cannot have ability to build with musl and builded with shared glibc ?
For example, k8smeta, etc.

**Comment by FedeDP** [comment]
> How falco interoperate with plugins, which cannot have ability to build with musl and builded with shared glibc ?

It cannot :/ unfortunately there is no way to dynamically load plugins; that's why the musl build won't support container too now that they've been moved to a plugin.
An idea (at least for the container support that is the most prominent missing feat of the musl build at this time) is to statically link the plugin instead (only for the musl build).
Libraries allow to statically load a plugin (basically by just filling up the normally-dynamically-loaded functions mapping table), thus it should not be impossible. We will play with this idea in the near future (hopefully).
