### ISSUE TITLE
[TRACKING] Falco `0.45.0` release

### ISSUE THREAD

**Issue by leogr** [falcosecurity/falco#3967]
# Falco 0.45.0 Release

Will keep this issue updated with the current status and progress.

## Date

Target release date: September 21st 2026

## Release Steps

The process is described in [this document](https://github.com/falcosecurity/falco/blob/master/RELEASE.md).

## External dependencies

- [ ] falcoctl
  - [x] driverkit `v0.23.2` bumped in falcoctl (CI green) 👉 https://github.com/falcosecurity/falcoctl/pull/1067
  - [x] `google.golang.org/grpc` bump 👉 https://github.com/falcosecurity/falcoctl/pull/1066
  - [x] drop the direct `github.com/docker/docker` dependency 👉 https://github.com/falcosecurity/falcoctl/pull/1065
  - [x] dismiss the 4 `github.com/docker/docker` advisories as not reachable (see the note below) 👉 done on September 3rd, no open Dependabot alerts left in falcoctl
  - [x] release 👉 https://github.com/falcosecurity/falcoctl/releases/tag/v0.14.0 (September 4th; assets, provenance, and `linux/amd64`+`linux/arm64` images verified)
  - [ ] bump `FALCOCTL_VERSION` in `falco/cmake/modules/falcoctl.cmake` (today `0.13.0`, target `0.14.0`)
- [ ] container plugin (**blocks libs**, see the note below)
  - already merged and awaiting a release: `fix(plugins/container): recognize systemd nerdctl cgroups`, the `go.podman.io/podman/v6` + `containerd v2.2.5` migration, and several `go-worker` dependency bumps (`runc`, `buildah`, `fulcio`, `x/net`, `x/crypto`, `grpc`)
  - [x] CI unblocked 👉 https://github.com/falcosecurity/plugins/issues/1510 (GitHub runner image regression, not our code; the test fix from https://github.com/falcosecurity/plugins/pull/1511 plus the image rollback: the re-run of the last failed e2e run on `main` is green on September 4th)
  - [x] safety check of the `main` build (`0.7.2`, commit `fca54d5e7`) against the released Falco `0.44.1`: plugin loads, all engines enabled, modern eBPF probe attached, `Terminal shell in container` fires with full container metadata (id, name, image repository and tag) 👉 done locally on September 4th, not covered by the plugins CI (which validates against `falco:0.41.3` and runs the e2e with `falco:master-debian`)
  - [x] decide which pending PRs go in:
    - [x] https://github.com/falcosecurity/plugins/pull/1501 - link `libresolv` so the plugin loads on glibc < 2.34 👉 fixes https://github.com/falcosecurity/plugins/issues/1500 and bumps the plugin to `0.7.2`
    - [x] https://github.com/falcosecurity/plugins/pull/1502 - resubscribe to the CRI container events stream 👉 fixes https://github.com/falcosecurity/plugins/issues/1499
    - [x] https://github.com/falcosecurity/plugins/pull/1020 - propagate engine initialization errors to the caller 👉 relates to https://github.com/falcosecurity/plugins/issues/1487; **excluded from `0.7.2`** (decision of September 4th): stale (changes requested, author inactive since January 2026), overlaps with the #1487 fix
    - [x] https://github.com/falcosecurity/plugins/pull/1486 - bump `moby/go-archive` to `0.3.0` in `go-worker`
    - [x] https://github.com/falcosecurity/plugins/pull/1506 - bump `google.golang.org/grpc` in `go-worker`
    - [x] https://github.com/falcosecurity/plugins/pull/1488 - bump `moby/buildkit` in `go-worker`
  - [x] CI guard for the `libresolv` linkage, so https://github.com/falcosecurity/plugins/issues/1500 cannot come back 👉 https://github.com/falcosecurity/plugins/issues/1512 fixed by https://github.com/falcosecurity/plugins/pull/1513 (both guards verified against the real artifact on `amd64` and `arm64`)
  - [x] dismiss the 8 `github.com/docker/docker` advisories as not reachable (4 on the container `go-worker`, 4 on `build/registry`; same reasoning as falcoctl, see the note below) 👉 done on September 4th
  - [x] fix the OCI publish step before tagging 👉 the `build/registry` tool no longer compiles since https://github.com/falcosecurity/plugins/commit/d54b16ac (`moby/go-archive` `0.3.0` removed the `Compression` alias still used by the `docker/docker` archive shim that driverkit `v0.23.1` drags in through falcoctl `v0.13.0`, `undefined: archive.Compression`); `Update Plugins-dev` has been red on `main` since September 1st, and the tag-triggered release runs the same reusable workflow, so the `container` OCI artifact would not be published. Fix: bump falcoctl to `v0.14.0` in `build/registry`, since driverkit `v0.23.2` no longer needs the shim 👉 https://github.com/falcosecurity/plugins/pull/1514 (verified on `main` on September 4th: `Update Plugins-dev` green end to end, OCI artifacts published and signed)
  - [x] fix the build step before tagging 👉 since September 4th every plugins build fails at `Install updated clang version`, on both architectures: Debian 11 reached end of life on August 31st and the `clang-19` binaries are gone from the `bullseye-security` pool while the index still lists them (404); the tag-triggered release runs the same reusable build workflow. Fix: pin `apt.llvm.org` before running `llvm.sh` 👉 https://github.com/falcosecurity/plugins/pull/1515. N.B. the `bullseye-security` index expires on September 7th, so the `debian:bullseye` build container may need a follow-up
  - [x] fix the build step again before tagging 👉 since the afternoon of September 4th the Debian archive removes ordinary `bullseye-security` binaries too (`gpgconf`, `libpython3.9-minimal`, `libperl5.32`), so every plugins build fails at `Install deps` on both architectures (e.g. https://github.com/falcosecurity/plugins/actions/runs/33886598084), release workflow included. Dropping the `bullseye-security` source is not enough (the image already ships the security versions of `libc6`, `perl-base`, `gpgv`) and `archive.debian.org` has no `bullseye-security` yet. Fix: take `bullseye-security` from the `snapshot.debian.org` mirror the image was built from 👉 https://github.com/falcosecurity/plugins/pull/1516 (verified locally in `debian:bullseye`, then on `main`: `Update Plugins-dev` green end to end on September 4th 👉 https://github.com/falcosecurity/plugins/actions/runs/33890804530). The base image needs a proper decision after the release
  - [ ] release 👉 currently shipped `0.7.1`; ready to tag `plugins/container/v0.7.2` at `main` commit `88f3c418` (September 4th: same plugin sources as the safety-checked build, `Update Plugins-dev` green end to end including the OCI publish and signing 👉 https://github.com/falcosecurity/plugins/actions/runs/33890804530)
  - [ ] pin the new version in `libs/cmake/modules/container_plugin.cmake` (today `0.6.0`)
  - [ ] pin the new version in `falco/CMakeLists.txt` (today `0.7.1`)
- [ ] libs
  - [ ] `0.26.0` 👉 6 items still open (2 PRs, 4 issues); the tag can slip to Wednesday September 9th at the latest, to let https://github.com/falcosecurity/libs/pull/3086 in (see the driver note below); https://github.com/falcosecurity/libs/pull/3021 is under discussion with the author
  - [ ] once the last PR is merged: CI green on `master` (build, tests, and the kernel matrix), then a full test pass before tagging (Falco pinned to the candidate `master` commit with its own CI green)
  - [ ] bump `CONTAINER_VERSION` before tagging (see above)
- [ ] drivers
  - [ ] `TBD+driver` 👉 see the note below
- [x] driverkit
  - [x] `v0.23.2` 👉 https://github.com/falcosecurity/driverkit/releases/tag/v0.23.2
- [ ] k8smeta plugin
  - [ ] decide whether https://github.com/falcosecurity/plugins/pull/1489 (accept purely numeric Kubernetes node names; CI green, no review yet) goes in; low priority. If merged, a new release is needed; otherwise `0.4.1` stays, since only `CHANGELOG.md` changed since https://github.com/falcosecurity/plugins/releases/tag/plugins%2Fk8smeta%2Fv0.4.1
- [ ] rules
  - [ ] `falco-rules-5.2.0` 👉 needed since September 4th: https://github.com/falcosecurity/rules/pull/374 adds the `systemd_sensitive_file_readers` macro to the stable ruleset, which is a minor bump per https://github.com/falcosecurity/rules/blob/main/RELEASE.md#versioning-a-ruleset (the repo's checker agrees: `**Minor** changes: * Macro systemd_sensitive_file_readers has been added`); `required_engine_version: 0.57.0` is untouched; `main` CI green at `80880bd59`
  - [ ] `falco-sandbox-rules-6.2.0` 👉 https://github.com/falcosecurity/rules/pull/373 adds new sandbox rules (minor bump); Falco bundles the stable ruleset only, but we release it in the same round before `0.45.0` (decision of September 4th)
  - [x] `falco-incubating-rules-6.0.1` (no release needed) 👉 no incubating content changed since the tag
  - [ ] pin `falco-rules-5.2.0` in `falco/cmake/modules/rules.cmake` (today `falco-rules-5.1.0`)
  - [x] open rules PRs (https://github.com/falcosecurity/rules/pull/381, https://github.com/falcosecurity/rules/pull/367, https://github.com/falcosecurity/rules/pull/364, https://github.com/falcosecurity/rules/pull/363) 👉 deferred to after `0.45.0` (decision of September 4th)

N.B. `driver/API_VERSION` (`10.1.0`) and `driver/SCHEMA_VERSION` (`4.5.1`) are unchanged since `0.25.4`, so the versioning rules do not mandate a driver version bump. However, there is one functional driver change on `master` (`fix(modern_bpf): reduce BPF instruction count in auxmap__preload_event_header`), so on their own they would not require a new driver tag. Decision (September 4th): if https://github.com/falcosecurity/libs/pull/3086 lands in `0.26.0`, it bumps `driver/API_VERSION` to `11.0.0` (incompatible map layout for older userspace) and we cut `11.0.0+driver`, which means a full rebuild of the prebuilt drivers by the DBG and a `SCAP_MINIMUM_DRIVER_API_VERSION` move to `11.0.0`; otherwise we stick with `10.2.0+driver`.

N.B. Falco overrides `CONTAINER_VERSION` in its own `CMakeLists.txt`, so both that pin and the one in `libs/cmake/modules/container_plugin.cmake` have to be bumped.

N.B. Four `github.com/docker/docker` advisories (GHSA-rg2x-37c3-w2rh, GHSA-x86f-5xw2-fm2r, GHSA-vp62-88p7-qqf5, GHSA-pxq6-2prw-chj9) have **no patched version** on that module line, which is capped at `v28.5.2+incompatible` (the successor, `github.com/moby/moby/v2`, is still in beta). So no bump can close them. However, they are all **daemon-side** issues, and as @tuminoid already noted in https://github.com/falcosecurity/plugins/issues/1349#issuecomment-4533218666, we only import the client side. Verified: the whole transitive `docker/docker` surface of falcoctl is `api`, `api/types/*`, `client`, and `pkg/homedir` - no daemon packages at all. The same holds for the container plugin, which imports only `api/types/{container,events,filters,image}` and `client`. So the right outcome is a dismissal as *not reachable*, not a version bump, and this does not block 0.45.

## Manual Testing Action Items

- [ ] Running Falco on Kubernetes with the official Helm Charts
- [ ] Running Falco on Kubernetes with the official operator
- [ ] Running Falco from RPM and DEB artifacts
- [ ] Running Falco in a container with the official images
- [ ] Running/fuzzing Falco with multiple event sources active in parallel
- [ ] Running/fuzzing Falco with variable syscall buffer dimension
- [ ] Running Falco in all officially-supported architectures (x86_64, ARM64)
- [ ] Running Falco with the supported drivers (kmod, modern eBPF, scap files)
- [ ] Test Falco with event generator
- [ ] Test that plugins are correctly loaded
- [ ] Test memory and CPU usage (with Valgrind and other tools)
- [ ] Test latest version of driver loader
- [ ] Test that `k8smeta` plugin works as expected
- [ ] Test that all Falco CLI options work as expected
- [ ] Check that Falco log messages are correct and consistent
- [ ] Test that Falco ruleset loading and validation works as expected
- [ ] Test the new invalid UTF-8 sequence handling 👉 https://github.com/falcosecurity/falco/commit/65273dae

## Action Items

- [ ] **Pre-Release**
  - [ ] Milestone
    - [x] Assign the missing milestone to merged PRs and closed issues since `0.44.0` 👉 https://github.com/falcosecurity/falco/pull/3956, https://github.com/falcosecurity/falco/pull/3948, and https://github.com/falcosecurity/falco/pull/3933 moved to `0.45.0`; the 2 `release/0.44.x` cherry-picks belong to the patch milestones; none of the 12 closed issues needs one (stale-bot closures, spam, or user-side fixes)
    - [x] Check the release note block of every merged PR in the milestone 👉 16 merged PRs checked; notes fixed on https://github.com/falcosecurity/falco/pull/3942 (engine `0.63.0` breaking change now spelled out), https://github.com/falcosecurity/falco/pull/3943 (Conventional Commits form), and https://github.com/falcosecurity/falco/pull/3924 (configs still setting `container_engines` now get a schema warning). To be repeated for PRs merged after September 3rd
  - [ ] Code freeze in falcosecurity/falco
  - [ ] Open release branch in Falco and protect it
  - [ ] See `External dependencies` task lists
  - [ ] Bump `FALCOSECURITY_LIBS_VERSION`, `DRIVER_VERSION`, `FALCOCTL_VERSION`, and `CONTAINER_VERSION` to the final tags 👉 PR to be opened once everything is tagged (https://github.com/falcosecurity/falco/pull/3957 only moved libs and driver to `master` commit `1a1d1e7e`)
  - [ ] Prebuilt drivers publish
  - [ ] Code thaw in falcosecurity/falco
  - [ ] Changelog on the release branch
  - [ ] Cherry-pick the changelog on master
- [ ] **Release**
  - [ ] Github Release in the Falco repo
    - [ ] `0.45.0`
- [ ] **Website**
  - [ ] Create new snapshot for `v0.44`
  - [ ] Protect snapshot branch
  - [ ] Bump `config/_default/versions/params.yaml`
  - [ ] Merge the release blog post
  - [ ] Merge all necessary documentation PRs
    - [ ] update the RHEL 8 `LD_PRELOAD=/lib64/libresolv.so.2` note, no longer needed with container plugin `0.7.2` 👉 https://github.com/falcosecurity/falco-website/issues/1582
- [ ] **Helm**
  - [ ] Release a new helm chart version
  - [ ] Update helm chart documentation
  - [ ] Decide whether to bump the subchart constraints (`falcosidekick`, `k8s-metacollector`, and `falco-talon` are all pinned to older versions than the published ones)
- [ ] **Operator**
- [ ] **Announcements**
  - [ ] mailing list
  - [ ] blog post
  - [ ] slack channel
- [ ] **Post-Release**
  - [ ] Archive community call meeting notes
  - [ ] Close the resolved issues after the tag and move the unresolved ones under a new milestone
  - [ ] Update supported fields and syscall documentation
  - [ ] add Falco version to the rules CI

## Breaking changes

- `FALCO_ENGINE_VERSION` moved from `0.62.0` to `0.63.0` 👉 https://github.com/falcosecurity/falco/commit/65273dae (`feat(userspace)!: improve invalid UTF-8 sequence handling`). `FALCO_ENGINE_CHECKSUM` is unchanged, so no field, event, or driver schema changed. This needs an explicit mention in the release notes and in the blog post.

## Miscs

/milestone 0.45.0

/kind documentation

## Release blocking PRs

- the final version-pin PR in falcosecurity/falco (to be opened, see the Pre-Release list above)

## Candidates to evaluate before the code freeze

- https://github.com/falcosecurity/falco/issues/3955 - modern eBPF repeatedly terminates while parsing syscall events on Linux 7.0 (affects `0.44.0` and `0.44.1`) 👉 fix in https://github.com/falcosecurity/libs/pull/3086 (milestone `0.26.0`; on hold: `driver/API_VERSION` question open, kernel test matrix not run yet, `test-drivers-amd64` failing on the latest revision)
- https://github.com/falcosecurity/falco/issues/3737 - SIGSEGV when snapshotting metrics 👉 nice to have, it will not hold the release if the fix arrives late
- https://github.com/falcosecurity/falco/pull/3871 - open pidfile with `O_NOFOLLOW` to prevent symlink TOCTOU 👉 waiting on the author
- https://github.com/falcosecurity/libs/issues/2719 - potential race condition in `modern_bpf/auxmap` 👉 root cause of the item above, same fix https://github.com/falcosecurity/libs/pull/3086
- https://github.com/falcosecurity/libs/issues/3046 - wrong NULL check in `PPM_IOCTL_GET_VTID`/`GET_VPID` 👉 confirmed but harmless: kmod only, dead `/proc` fallback path (kernels < 4.1), `ns_of_pid()` cannot return NULL there. One-line driver fix, no PR yet; already in the `next-driver` milestone, so it just follows the driver-tag decision above
- https://github.com/falcosecurity/plugins/issues/1500 - `libcontainer.so` fails to load on glibc < 2.34 👉 fixed by https://github.com/falcosecurity/plugins/pull/1501, ships with container plugin `0.7.2`
- https://github.com/falcosecurity/plugins/issues/1487 - unbounded blocking in engine bootstrap hangs Falco startup

**Comment by leogr** [comment]
CI blocker: https://github.com/falcosecurity/plugins/issues/1510

**Comment by leogr** [comment]
> N.B. `driver/API_VERSION` (`10.1.0`) and `driver/SCHEMA_VERSION` (`4.5.1`) are unchanged since `0.25.4`, so the versioning rules do not mandate a driver version bump. However, there is one functional driver change on `master` (`fix(modern_bpf): reduce BPF instruction count in auxmap__preload_event_header`), so we still have to decide whether to cut a new driver tag or stick with `10.2.0+driver`. This also determines whether the DBG has to rebuild all the prebuilts.

@gnosek if you have opnion on this ☝️ let me know, please 🙏

**Comment by leogr** [comment]
Weekly recap :point_down:

- falcoctl `v0.14.0` released :rocket: (driverkit `v0.23.2`, no more direct `docker/docker` dependency, no open Dependabot alerts left)
- container plugin `0.7.2` is ready content-wise (`libresolv` fix, CRI resubscribe, nerdctl cgroups, podman v6 + containerd 2.2.5). The tag is blocked by the plugins CI, which broke three times this week for reasons unrelated to the plugin itself (runner image regression, OCI publish tool, Debian 11 EOL). Last fix in https://github.com/falcosecurity/plugins/pull/1516
- libs `0.26.0`: 6 items left, tag by Wednesday September 9th at the latest. The driver tag (`10.2.0+driver` vs `11.0.0+driver`) depends on https://github.com/falcosecurity/libs/pull/3086
- rules: several PRs merged this week, so `falco-rules-5.2.0` and `falco-sandbox-rules-6.2.0` will be released before `0.45.0`. The remaining open PRs are deferred to after the release
- k8smeta plugin: no release needed atm; this may change if we merge https://github.com/falcosecurity/plugins/pull/1489 (low priority)
- Falco: milestone and release notes cleaned up; the `FALCO_ENGINE_VERSION` bump to `0.63.0` is the breaking change to call out
- Next week: container plugin tag, then libs + driver tags, rules releases, and the final version-pin PR in Falco

The checklist above is up to date. The release date is still on track.

**Comment by leogr** [comment]
UPDATE

- Container plugin `0.7.2`, falcoctl `v0.14.0`, and rules `5.2.0` / sandbox `6.2.0` are out.
- libs `0.26.0` + `11.0.0+driver`: five PRs merged today, two left (both waiting for reviews). Still aiming to tag by Wednesday.
  - falcosecurity/libs#3086
  - falcosecurity/libs#3016
- N.B. before generating the driver configs, double check the kernel-crawler lists contain `centos` 👉 falcosecurity/kernel-crawler#261
- Falco, merged today:
  - #3871
  - #3935
  - #3936
  - #3970
- Falco, waiting for a second review:
  - #3972
  - #3973
  - #3974
  - #3947
  - #3975
- Plugins: k8smeta `0.4.2` via falcosecurity/plugins#1517, then the bulk release of the other 7 plugins.

Code freeze date to follow.

**Comment by leogr** [comment]
cc @falcosecurity/core-maintainers

**Comment by leogr** [comment]
UPDATE

- libs `0.26.0` + `11.0.0+driver`: all the remaining PRs merged today, milestone empty. Release branch `release/0.26.x` created and RCs out 👉
  - https://github.com/falcosecurity/libs/releases/tag/0.26.0-rc1
  - https://github.com/falcosecurity/libs/releases/tag/11.0.0-rc1%2Bdriver
- Kernel matrix green on the driver RC. Falco pinned to the RCs (engine version bumped to `0.65.0` since the driver schema changed), CI running 👉 #3971
- Final tags tomorrow, once the Falco CI is green.
- Falco, merged today:
  - #3947
  - #3972
  - #3973
  - #3974
- Scorecard is green again on `master`.
- Falco issues closed today:
  - #3725
  - #3568
  - #3842
- #3955 👉 root cause confirmed, fixed by falcosecurity/libs#3086 (in `0.26.0`)
- Milestone triage done: five issues moved to `0.46.0`, nothing else in flight for `0.45.0`.
- Plugins: k8smeta `0.4.2` bump merged 👉 falcosecurity/plugins#1517, tag next, then the bulk release of the other 7 plugins.
- Waiting for a review:
  - falcosecurity/test-infra#2061 (release branch protection)
  - falcosecurity/kernel-crawler#263 (`photon` x86_64 fix)
- N.B. drivers: `centos` is back in the kernel-crawler lists, `debian` aarch64 is still partial and the `photon` x86_64 fix is in review, so the DBG config PR stays on hold until both lists are complete 👇
  - falcosecurity/kernel-crawler#262
  - falcosecurity/kernel-crawler#263

**Comment by leogr** [comment]
📣 Falco `0.45.0-rc1` is out 👉 https://github.com/falcosecurity/falco/releases/tag/0.45.0-rc1

It ships libs `0.26.0-rc1` and driver `11.0.0-rc1+driver`, falcoctl `0.14.0`, container plugin `0.7.2`, and rules `5.2.0`.

Please give it a try and report anything weird here 🙏
- container image `falcosecurity/falco:0.45.0-rc1`
- DEB packages 👉 https://download.falco.org/?prefix=packages/deb-dev/
- RPM packages 👉 https://download.falco.org/?prefix=packages/rpm-dev/

N.B. The final `0.45.0` will move to the libs `0.26.0` and `11.0.0+driver` tags and to the container plugin `0.7.3`.

**Comment by leogr** [comment]
cc @falcosecurity/core-maintainers

**Comment by leogr** [comment]
Update of the day (Sep 9) 👇

Merged today
- https://github.com/falcosecurity/libs/pull/3097
- https://github.com/falcosecurity/libs/pull/3098
- https://github.com/falcosecurity/falco/pull/3894
- https://github.com/falcosecurity/falco/pull/3931
- https://github.com/falcosecurity/charts/pull/1055

libs `release/0.26.x` is complete and green: `0.26.0-rc2` follows once the container plugin `0.7.3` is pinned there.

Container plugin: the fix PR went through a further review round today, the fixes are in and it is ready for review 👉 https://github.com/falcosecurity/plugins/pull/1534
Next: tag `0.7.3`, pin it in libs and Falco, then `0.45.0-rc2` with libs `0.26.0-rc2` and falcoctl `0.14.1`, expected in 1-2 days.

Chart PRs waiting for reviews 🙏
- https://github.com/falcosecurity/falco/pull/3976
- https://github.com/falcosecurity/falco/pull/3977
- https://github.com/falcosecurity/falco/pull/3978
- https://github.com/falcosecurity/falco/pull/3946
- https://github.com/falcosecurity/k8s-metacollector/pull/227

Moved to 0.46.0
- https://github.com/falcosecurity/falco/pull/3930
- https://github.com/falcosecurity/falco/pull/3908
- https://github.com/falcosecurity/falco/pull/3934

Declined, the falcoctl credentials go through `envFrom`
- https://github.com/falcosecurity/falco/pull/3911

**Comment by leogr** [comment]
Update of the day 👇

Container plugin `0.7.3` and `0.7.4` are out, `0.7.4` is the one we ship 👉 https://github.com/falcosecurity/plugins/releases/tag/plugins%2Fcontainer%2Fv0.7.4

It carries the engine bootstrap timeout and lookup retry fixes, the `containerd` security update, and a fix for interrupted `containerd` inspections at startup. Tarballs, OCI artifact, and signature verified.

libs `0.26.0-rc2` is out 👉 https://github.com/falcosecurity/libs/releases/tag/0.26.0-rc2

It pins the container plugin `0.7.4` and carries the last fixes cherry-picked onto `release/0.26.x`. The driver stays at `11.0.0-rc1+driver`, since nothing changed under `driver/`.

Merged today
- https://github.com/falcosecurity/plugins/pull/1534
- https://github.com/falcosecurity/plugins/pull/1536
- https://github.com/falcosecurity/plugins/pull/1537
- https://github.com/falcosecurity/libs/pull/3099
- https://github.com/falcosecurity/libs/pull/3100
- https://github.com/falcosecurity/libs/pull/3102
- https://github.com/falcosecurity/libs/pull/3103
- https://github.com/falcosecurity/falco/pull/3983

Falco PRs waiting for reviews 🙏
- https://github.com/falcosecurity/falco/pull/3985 (pins for `0.45.0-rc2`: libs `0.26.0-rc2`, falcoctl `0.14.1`, container plugin `0.7.4`)
- https://github.com/falcosecurity/falco/pull/3986 (cherry-picks onto `release/0.45.x`: everything merged since `rc1`, pins included)
- https://github.com/falcosecurity/falco/pull/3984 (chart: `config.d` mount fix and the `9.2.0` component pins)

Next: `0.45.0-rc2`, likely tomorrow, once the sync PR is merged and `release/0.45.x` is green.

**Comment by leogr** [comment]
📣 Falco `0.45.0-rc2` is out 👉 https://github.com/falcosecurity/falco/releases/tag/0.45.0-rc2

It ships libs `0.26.0-rc2` and driver `11.0.0-rc1+driver`, falcoctl `0.14.1`, container plugin `0.7.4`, and rules `5.2.0`. Compared to `rc1`, it carries the last libs fixes and the container plugin fixes (engine bootstrap timeout, lookup retries, interrupted `containerd` inspections at startup, `containerd` security update).

Please give it a try and report anything weird here 🙏
- container image `falcosecurity/falco:0.45.0-rc2`
- DEB packages 👉 https://download.falco.org/?prefix=packages/deb-dev/
- RPM packages 👉 https://download.falco.org/?prefix=packages/rpm-dev/

N.B. The final `0.45.0` will move to the libs `0.26.0` and `11.0.0+driver` tags once cut.

**Comment by leogr** [comment]
UPDATE: the `0.45.0` milestone is completed at the moment, so the code freeze is reached 🥳

From now on, only fixes will be cherry-picked onto `release/0.45.x`. The only planned change left is the final libs `0.26.0` pin for `rc3`.

**Comment by leogr** [comment]
📣 Falco `0.45.0-rc3` is out 👉 https://github.com/falcosecurity/falco/releases/tag/0.45.0-rc3

It ships the final libs `0.26.0` and driver `11.0.0+driver`, falcoctl `0.14.2`, container plugin `0.7.4`, and rules `5.2.0`. Compared to `rc2`, it carries the last libs fixes (incl. the JSON output fix for malformed UTF-8 found on `rc2`), the packaging fix that restores services and drivers after an upgrade, and the falcoctl fix that preserves DKMS installations.

Please give it a try and report anything weird here 🙏
- container image `falcosecurity/falco:0.45.0-rc3`
- DEB packages 👉 https://download.falco.org/?prefix=packages/deb-dev/
- RPM packages 👉 https://download.falco.org/?prefix=packages/rpm-dev/

N.B. Unless something weird pops up, this is the last RC before the final `0.45.0` 🚀

**Comment by leogr** [comment]
Today's updates 👇

- `0.45.0-rc4` is out 👉 https://github.com/falcosecurity/falco/releases/tag/0.45.0-rc4
- it ships the last fixes merged on `master` after `rc3`, the SIGHUP reload fix and the Unix socket reload control included
- the prebuilt drivers for `11.0.0+driver` are being published, see the checklist above for the status

Also, the final release may be delayed by a few days, since:

- we want to deeply test some last minute fixes
- we are migrating our infra from AWS to OCI, and this process requires updating many `test-infra` components, including Prow. This may create temporary issues, and we won't release Falco until everything is settled

Kudos to @c2ndev for the great on-going work on `test-infra` 🙏

Thanks for your patience 😅
