### ISSUE TITLE
ARM64 Build

### ISSUE THREAD

**Issue by nfrush** [falcosecurity/falco#520]
Hey,

Can you guys release ARM64 builds? I mainly run Kubernetes on ~50-100 ARM clusters and wanted to test Falco out. I did try compiling myself, but gRPC was throwing an odd error during compilation at me (I fixed the errors thrown by protobuf by providing my own compiled installation of protobuf on the system). I assume I could maybe compile newer grpc and provide it on the system... but I'd rather not hack together a build process to get a build for a single release.

Many thanks in advance.

**What would you like to be added**:
Deb, RPM and pre-built packages for ARM7 and ARM8.

**Why is this needed**:
We want to have packages for other platforms than X86_64 - ARM7 and ARM7 both seem platforms on which many users want to try Falco.

**Related issues**
- #586

**Comment by fntlnz** [comment]
@nfrush I edited this issue to match the new template we have, there's a whole set of improvements to the build system from @leodido in #719 - after that we will be able to include more architectures in an easier way.

**Comment by fntlnz** [comment]
I'm closing this since right now ARM support is not in the core maintainers team priorities and since February no one seemed to want to pickup this one.

@nfrush feel free to reopen if you think you can submit a PR to make this happen and feel free to continue the discussion even after the close.

**Comment by kris-nova** [comment]
I am working on this now - I believe the problem is with the lua dependencies

I will report back once I get it building

**Comment by kris-nova** [comment]
So I have Falco working on aarch64. The issue was that the version of `luajit` that was being bundled into the build isn't compatible with arm aarch64 architecture. 

There is more detail on the official luajit website, but I tried to compile with both lua 5.1.5 and luajit 2.0.0 as the documentation for ARM suggests.

Both of those failed. Lua failed the check for being a valid lua interpretor, and 2.0.0 and 2.0.5 both returned the error documented [here](https://github.com/draios/sysdig/issues/697/)

```
==== Building LuaJIT 2.0.3 ====
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
  ^
lj_arch.h:279:2: error: #error "No target architecture defined"
 #error "No target architecture defined"
  ^
lj_arch.h:55:2: error: #error "No support for this architecture (yet)"
 #error "No support for this architecture (yet)"
```

**Comment by fntlnz** [comment]
@kris-nova why is this closed? Am I missing something?

**Comment by kris-nova** [comment]
Ah sorry I must have hit the wrong button. I have Falco compiling on armv7 and am going to have a blog out by the end of the week and demo on setns this Friday.

Stay tuned for links and documentation on how to do this.

![Screenshot from 2020-04-29 19-43-12](https://user-images.githubusercontent.com/13757818/80669836-38089e00-8a5a-11ea-8769-7e4d4d279bbc.png)

**Comment by xUnholy** [comment]
@kris-nova I'm also a user trying to get ARM(64) falco working, you were going to release a blog of sorts, did you ever manage to release it? OR document somewhere your process to follow?

**Comment by xUnholy** [comment]
Bump - Can we label this so it doesn't go stale?

**Comment by sfxworks** [comment]
Looking forward to this update. Homelab consists of mix of arm & amd.

**Comment by alexellis** [comment]
@fntlnz encouraged me to try building Falco on my RPi4. I used Ubuntu 20 and the 64-bit image. The device has 4GB of RAM.

I'm getting the following error.

```
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/filtered_re2.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/mimics_pcre.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/nfa.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/onepass.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/parse.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/perl_groups.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/prefilter.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/prefilter_tree.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/prog.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/re2.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/regexp.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/set.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/simplify.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/stringpiece.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/tostring.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/unicode_casefold.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/re2/unicode_groups.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/util/pcre.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/util/rune.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/re2/util/strutil.o
[C]       Compiling third_party/upb/upb/decode.c
[C]       Compiling third_party/upb/upb/encode.c
[C]       Compiling third_party/upb/upb/msg.c
[C]       Compiling third_party/upb/upb/port.c
[C]       Compiling third_party/upb/upb/table.c
[C]       Compiling third_party/upb/upb/upb.c
[AR]      Creating /home/ubuntu/falco/grpc-prefix/src/grpc/libs/opt/libupb.a
ar: creating /home/ubuntu/falco/grpc-prefix/src/grpc/libs/opt/libupb.a
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/upb/upb/decode.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/upb/upb/encode.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/upb/upb/msg.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/upb/upb/port.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/upb/upb/table.o
a - /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/upb/upb/upb.o
[CXX]     Compiling third_party/abseil-cpp/absl/base/dynamic_annotations.cc
c++: error: unrecognized command line option ‘-maes’
c++: error: unrecognized command line option ‘-msse4’
make[4]: *** [Makefile:2968: /home/ubuntu/falco/grpc-prefix/src/grpc/objs/opt/third_party/abseil-cpp/absl/base/dynamic_annotations.o] Error 1
make[3]: *** [CMakeFiles/grpc.dir/build.make:113: grpc-prefix/src/grpc-stamp/grpc-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:848: CMakeFiles/grpc.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:6062: userspace/falco/CMakeFiles/falco.dir/rule] Error 2
make: *** [Makefile:2643: falco] Error 2
ubuntu@ubuntu:~/falco$ uname -a
Linux ubuntu 5.4.0-1015-raspi #15-Ubuntu SMP Fri Jul 10 05:34:24 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux
ubuntu@ubuntu:~/falco$ 
[1] 0:bash*              
```

Also pinging @kris-nova for follow-up in the week.
